### ISSUE TITLE
Additional accessibility

### ISSUE THREAD

**Issue by paskal** [kAworu/octostrap3#38]
Inspired by getnikola/nikola#1345, [here](http://getbootstrap.com/getting-started/#accessibility) is the information, I'll quote it:
> **Skip navigation**

> If your navigation contains many links and comes before the main content in the DOM, add a `Skip to main content link` immediately after your opening `<body>` tag. ([read why](http://a11yproject.com/posts/skip-nav-links/))

    <body>
      <a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>
      <div class="container" id="content">
        The main page content.
      </div>
    </body>

I think we might adopt this feature. @kAworu, if you'll approve this, I'll prepare a pull request.

**Comment by kAworu** [comment]
Hi Roman and Paskal, happy new year !

Twitter Bootstrap does not generate HTML markup, it "only" provide JS/CSS tools. In the documentation they've been adding ARIA roles since a while now, but that does not help much for markup already existing.

Perhaps the best way to go is to get documentation about the most important ARIA roles and landmark and implement them step by step. In that way @roman01la could you please point out some documentation you find useful to learn about ARIA implementation ?

Thanks to you both and take care.

**Comment by paskal** [comment]
@kAworu, some time ago Roman pointed me to [this document](http://w3c.github.io/aria-in-html/ "Using WAI-ARIA in HTML") which have a lot of answers to questions about using ARIA but right now I don't have enough time to carefully read it.

**Comment by kAworu** [comment]
@paskal Thank you it's useful to have the link in this issue even though it won't be fixed "right now" :+1:

**Comment by paskal** [comment]
I've checked theme again with two screen readers, they navigate it fine, HTML of octopress itself and of this particular theme is fine already. Let's close this one.
