### ISSUE TITLE
Disable responsiveness?

### ISSUE THREAD

**Issue by inem** [kAworu/octostrap3#48]
It looks like it is unachievable by changing some variables in sass/_custom/*.scss files
Can you give me quick idea how to do it?

**Comment by kAworu** [comment]
Hi @inem,

I would guess "responsiveness" is handled exclusively by CSS `@media` queries, so `git grep @media` into the octostrap repo would give you some hints. If I were you I would try to go in two steps:

1. `git grep @media sass/` would yield where octostrap care about `only screen and blabla width`, you could override them on your installed "copy" of the theme (wether they're in a _custom_ directory is actually not that relevant since you get to merge your changes at each theme install anyway — that's just how octopress themes work at the moment as far as I know)
2. Generate a "non-responsive" bootstrap tarball that would be extracted in your _source/assets/bootstrap/dist_ directory. Again, that would make theme upgrade somehow painful.

have fun !
Alex.
